name: swe_reler
description: Application for the final work of the software engineering course
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-VariableFont_wght.ttf
  assets:
    - assets/logo34-white.png
    - assets/logo78-black.png
    - assets/landing-page/introduction-background.jpeg
    - assets/landing-page/pick-a-plan.png
    - assets/landing-page/receive-at-home.png
    - assets/landing-page/sit-and-relax.png
    - assets/landing-page/whats-in-the-box.jpeg
    - assets/landing-page/pannel-shape.png
    - assets/landing-page/arrow1.png
    - assets/landing-page/arrow2.png
